vim.keymap.set("n", "<leader>md", "<cmd>MarkdownPreview<CR>")
vim.keymap.set("n", "<leader>mf", "<cmd>ObsidianFollowLink<CR>")
vim.keymap.set("n", "<leader>ml", "<cmd>ObsidianLink <CR>")
vim.keymap.set("n", "<leader>mn", "<cmd>ObsidianNew <CR>")
vim.keymap.set("n", "<leader>mt", "<cmd>:lua ToggleMarkdownTex()<CR>")
